# Generated by Django 3.2.6 on 2021-09-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
