# Generated by Django 3.2.6 on 2021-10-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_default_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_email_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='default_full_name',
        ),
    ]
