# Generated by Django 3.2.6 on 2021-09-14 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('header_image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('intro_paragraph_1', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(100)])),
                ('intro_paragraph_2', models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(100)])),
                ('subheading_1', models.CharField(max_length=80)),
                ('blog_content_1', models.TextField(validators=[django.core.validators.MinLengthValidator(250)])),
                ('subheading_2', models.CharField(max_length=80)),
                ('blog_content_2', models.TextField(validators=[django.core.validators.MinLengthValidator(250)])),
                ('blog_content_3', models.TextField(validators=[django.core.validators.MinLengthValidator(250)])),
                ('blog_image_1', models.ImageField(upload_to='')),
                ('subheading_3', models.CharField(max_length=80)),
                ('blog_content_4', models.TextField(validators=[django.core.validators.MinLengthValidator(250)])),
                ('blog_content_5', models.TextField(validators=[django.core.validators.MinLengthValidator(250)])),
                ('blog_content_6', models.TextField(validators=[django.core.validators.MinLengthValidator(250)])),
                ('blog_image_2', models.ImageField(upload_to='')),
                ('subheading_4', models.CharField(blank=True, max_length=55, null=True)),
                ('blog_content_7', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)])),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
