# Generated by Django 3.2.6 on 2021-09-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210915_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
