# Generated by Django 3.2.6 on 2021-09-16 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_1',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_2',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_3',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_4',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_5',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_6',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='intro_paragraph_2',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subheading_1',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subheading_2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subheading_3',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
