# Generated by Django 3.2.6 on 2021-09-30 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210930_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['published_date']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_1',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_3',
            field=models.TextField(default=None, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_4',
            field=models.TextField(blank=True, default=None, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_5',
            field=models.TextField(blank=True, default=None, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_6',
            field=models.TextField(blank=True, default=None, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_content_7',
            field=models.TextField(blank=True, default=None, validators=[django.core.validators.MinLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image_1',
            field=models.ImageField(blank=True, default=None, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='blog_image_2',
            field=models.ImageField(blank=True, default=None, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='header_image',
            field=models.ImageField(default=None, null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='intro_paragraph_2',
            field=models.TextField(blank=True, default=None, max_length=500, validators=[django.core.validators.MinLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subheading_3',
            field=models.CharField(blank=True, default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subheading_4',
            field=models.CharField(blank=True, default=None, max_length=55),
        ),
    ]
