# Generated by Django 3.2.6 on 2021-10-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210930_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
