# Generated by Django 3.2.6 on 2021-09-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=75)),
                ('about_content_1', models.TextField(max_length=600)),
                ('about_content_2', models.TextField(max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='instructors')),
            ],
        ),
    ]
