# Generated by Django 3.2.6 on 2021-09-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_rename_team_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='about',
            field=models.TextField(max_length=900),
        ),
    ]
