# Generated by Django 3.2.6 on 2021-09-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_itinerarydays_itineraryday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itineraryday',
            name='itinerary',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='ItineraryDay',
        ),
    ]
