# Generated by Django 3.2.6 on 2021-09-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210921_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryday',
            name='day_6',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_6_data',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_7',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_7_data',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_7_overview',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_8',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_8_data',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_8_overview',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
