# Generated by Django 3.2.6 on 2021-09-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210922_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='day_1_hotel',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_1_meal',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_2_hotel',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_2_meal',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_3_hotel',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_3_meal',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_4_hotel',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_4_meal',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_5_hotel',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_5_meal',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_6_hotel',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_6_meal',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_7_hotel',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_7_meal',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_8_hotel',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='itineraryday',
            name='day_8_meal',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_1_data',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_2_data',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_3_data',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_4_data',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_5_data',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_6_data',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_6_overview',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='itineraryday',
            name='day_8_data',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
