# Generated by Django 3.2.6 on 2021-10-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210923_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flights', models.TextField(blank=True, max_length=800, null=True)),
                ('visa', models.TextField(blank=True, max_length=300, null=True)),
                ('group_management', models.TextField(blank=True, max_length=800, null=True)),
                ('trail_running_1', models.TextField(blank=True, max_length=800, null=True)),
                ('trail_running_2', models.TextField(blank=True, max_length=800, null=True)),
                ('temperature', models.TextField(blank=True, max_length=500, null=True)),
                ('luggage', models.TextField(blank=True, max_length=800, null=True)),
                ('holiday', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
