# Generated by Django 3.2.6 on 2021-10-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'FAQ'},
        ),
    ]
